### ISSUE TITLE
Fedora 37 stuck on "Fix Grub.conf Perms"

### ISSUE THREAD

**Issue by Surferlul** [Nova1545/gnome-shell-extension-customreboot#2] opened 2022-11-24 01:12 UTC
When I click "Fix Grub.conf Perms" an Authorization Prompt pops up. Afterward, the extension still says "Fix Grub.conf Perms". Reboot doesn't fix this.

**Comment by Nova1545** [comment] 2022-11-24 01:55
Can you confirm that `/boot/grub/grub.cfg` or `/boot/grub2/grub.cfg` exists? If it does, confirm that the permissions match this:
![image](https://user-images.githubusercontent.com/43554977/203676059-32fed7fd-602e-4df0-820e-9ac6051a1a36.png)
If they don't, try setting them by hand
`sudo chmod 644 /boot/grub/grub.cfg` (Change grub for grub2 if needed)
And reload the extension

**Comment by Nova1545** [comment] 2022-11-24 03:11
Running Fedora 37 in a vm has revealed that even when `/boot/grub2/grub.cfg` is readable by anyone the system does not allow you to read it. 
The only way I found around this was making the entire `/boot` folder readable and make it owned by the current user, I, however, don't think this is a good idea in a normal context.

Another implementation will be needed to fix this

**Comment by skewty** [comment] 2022-12-02 12:51
What about sticky user (SUID) on a script that is run by this app (owned by root) as a possible work around?
https://www.redhat.com/sysadmin/suid-sgid-sticky-bit

**Comment by Nova1545** [comment] 2023-04-08 23:22
> What about sticky user (SUID) on a script that is run by this app (owned by root) as a possible work around? https://www.redhat.com/sysadmin/suid-sgid-sticky-bit

If I understand this correctly, root will still be needed to read the file no?

**Comment by victor-borges** [comment] 2023-04-14 23:34
Is `efibootmgr` a valid approach? 

![image](https://user-images.githubusercontent.com/46226318/232167612-f16dd677-5256-4b8c-8568-87982207d40c.png)

**Comment by Nova1545** [comment] 2023-04-15 14:50
That should work yes, I take it your on a Fedora system? Cause as long as it works there than yeah, I just have to build a parser for the script output and that's Fedora working again. Edit: I somehow didnt see the fact that the last boot entry is fedora...

**Comment by AdaStaysSilly** [comment] 2023-04-26 10:06
@Nova1545

> > What about sticky user (SUID) on a script that is run by this app (owned by root) as a possible work around? https://www.redhat.com/sysadmin/suid-sgid-sticky-bit
> 
> If I understand this correctly, root will still be needed to read the file no?

Yeah, grub.conf only has read perms for root

> That should work yes, I take it your on a Fedora system? Cause as long as it works there than yeah, I just have to build a parser for the script output and that's Fedora working again. Edit: I somehow didnt see the fact that the last boot entry is fedora...

efibootmgr works on current fedora systems (38 at time of reply) without superuser rights

**Comment by Nova1545** [comment] 2023-05-20 05:58
The latest version of the extension should fix the problems with Fedora [Version 5](https://github.com/Nova1545/gnome-shell-extension-customreboot/releases/tag/5.0). Should be available to update to from gnome-extensions in a few hours from now (Currently 2am here).

Before I close this issue, could someone just confirm that this fixes the issues and allows the extension to work as intended?

**Comment by FarisZR** [comment] 2023-05-20 19:28
![image](https://github.com/Nova1545/gnome-shell-extension-customreboot/assets/35614734/00f31efc-590e-4f28-979d-4be274cfa2ce)

For some reason EFIbootmgr is not working for me on Fedora 38 workstation, encrypted with LUKS if that matters.

**Comment by Nova1545** [comment] 2023-05-20 19:33
@FarisZR Could you post the output of `efibootmgr` from a terminal?

**Comment by FarisZR** [comment] 2023-05-20 19:53
I'm not on my PC at the moment, but it was working fine, with all boot options listed.

**Comment by Nova1545** [comment] 2023-05-20 21:11
Let me setup a proper Fedora install (Was using a vm) and investigate a bit

**Comment by Nova1545** [comment] 2023-05-21 15:48
@FarisZR 
The extension was having an issue finding the executable. This [release](https://github.com/Nova1545/gnome-shell-extension-customreboot/releases/tag/7.0) should fix the issues with efibootmgr. Could you test it for me? (Worked on my Fedora install)

On another note: The gnome extensions page is having issues, I unfortunatly cannot upload the newest release at this time

**Comment by FarisZR** [comment] 2023-05-27 13:07
can confirm, its working now, though it asks for the password every time I want to reboot.

**Comment by AdaStaysSilly** [comment] 2023-05-27 13:18
I can also confirm this exact behavior

**Comment by Nova1545** [comment] 2023-05-28 02:30
The password for every reboot is the way it has always worked. #1 will eventually make it so you don't need a password

**Comment by Nova1545** [comment] 2023-05-28 02:30
Closing this issue as resolved

**Closed as completed by Nova1545** 2023-05-28 02:30 UTC

**Comment by kurtbahartr** [comment] 2024-10-12 13:01
I'm pretty much new to this extension as a current Ubuntu user, but having used Fedora before, I assume this issue is because of Fedora's nature of using enforcing SELinux, like Android, instead of AppArmor, like Ubuntu and the likes.

SELinux is far more strict than AppArmor and has the potential to break not just 3rd party software like this but also an entire hardware stack when not configured in the desired way before going enforcing - I'm sure many Android custom ROM maintainers will understand what I mean here.

To fix this in Fedora, someone (preferably not me ~~as I have PTSD from SELinux thanks to Google's take on AOSP~~) has to look at the rules Fedora imposes on `/boot` directory and its contents.

On contrary to all of this, making the file readable alone doesn't work but it does when combined with ownership change because, I assume, it's just the SELinux rules being configured to allow the file to be accessible only by the file owner's UID.

You could in theory replace SELinux with AppArmor the Arch way and it's very likely to work with cases like this, but I have no idea how much of a secure and reliable system you'll get this way - Might as well install something like Ubuntu instead while at it.
